# Generated by Django 3.2.6 on 2022-03-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0005_newsitem_source_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='link',
            field=models.URLField(max_length=300),
        ),
    ]
