# Generated by Django 3.2.6 on 2022-03-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0006_alter_newsitem_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='star_rating',
            field=models.IntegerField(default=5),
        ),
    ]
