# Generated by Django 3.2.6 on 2022-03-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0010_publication_stories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication_stories',
            options={'verbose_name_plural': 'Publication_Stories'},
        ),
    ]
