# Generated by Django 3.2.6 on 2022-03-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0011_alter_publication_stories_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.URLField(default='https://www.clipartmax.com/png/middle/265-2655834_work-in-progress-icon.png'),
        ),
    ]
