# Generated by Django 3.2.6 on 2022-03-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0012_publication_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image_file',
            field=models.CharField(default='wip.jpg', max_length=20),
        ),
    ]
