# Generated by Django 3.2.6 on 2022-04-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0015_alter_publication_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image_source',
            field=models.CharField(default='ShuggyMcguggy on Unsplash', max_length=50),
        ),
    ]
