# Generated by Django 3.2.6 on 2022-05-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0018_pageexport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageexport',
            name='local_dir',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pageexport',
            name='target_page_url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
