# Generated by Django 3.2.6 on 2023-01-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0020_pageexport_local_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSS_feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(default=' ', max_length=100)),
                ('feed_url', models.URLField()),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_pub_date', models.DateTimeField()),
                ('image_url', models.URLField()),
                ('is_live', models.BooleanField()),
                ('total_publications', models.IntegerField()),
            ],
        ),
    ]
